#pragma once

#include "../../lib/include/managerbase.h"
#include "../../lib/include/unit.h"
#include "./hal/include/unit.h"

namespace womolin::board
{
   
   using namespace womolin::lib::interface::hal;
   using namespace womolin::lib::signal;
   using namespace womolin::lib::unit;
   using namespace womolin::lib::manager;
   using namespace womolin::board::hal;

   class HalManager : public LibManagerBase 
   {
      public:
         HalManager( ILibSerial & serial );
         ~HalManager() = default;

      private:
         // properties of the board
         HalOutput HAL_BIRELAY_0 { HalOutput( DEV_ID::BIRELAY_0 ) }; 
         HalOutput HAL_BIRELAY_1 { HalOutput( DEV_ID::BIRELAY_1 ) }; 
         HalOutput HAL_BIRELAY_2 { HalOutput( DEV_ID::BIRELAY_2 ) }; 
         HalOutput HAL_BIRELAY_3 { HalOutput( DEV_ID::BIRELAY_3 ) }; 

         HalInput HAL_BIRELAY_0_STATUS { HalInput( DEV_ID::BIRELAY_0 ) }; 
         HalInput HAL_BIRELAY_1_STATUS { HalInput( DEV_ID::BIRELAY_1 ) }; 
         HalInput HAL_BIRELAY_2_STATUS { HalInput( DEV_ID::BIRELAY_2 ) }; 
         HalInput HAL_BIRELAY_3_STATUS { HalInput( DEV_ID::BIRELAY_3 ) }; 


         // will be generated by code generator
         // WomoLIN Units with allcation to the board units HAL_...
         LibOutput          LIB_BIRELAY_1{ LibOutput( HAL_BIRELAY_0 ) };
         LibOutput          LIB_BIRELAY_2{ LibOutput( HAL_BIRELAY_1 ) };
         LibOutput          LIB_BIRELAY_3{ LibOutput( HAL_BIRELAY_2 ) };
         LibOutput          LIB_BIRELAY_4{ LibOutput( HAL_BIRELAY_3 ) };

         LibInput          LIB_BIRELAY_1_STATUS{ LibInput( HAL_BIRELAY_0_STATUS) };
         LibInput          LIB_BIRELAY_2_STATUS{ LibInput( HAL_BIRELAY_1_STATUS) };
         LibInput          LIB_BIRELAY_3_STATUS{ LibInput( HAL_BIRELAY_2_STATUS) };
         LibInput          LIB_BIRELAY_4_STATUS{ LibInput( HAL_BIRELAY_3_STATUS) };


         // User Signals, e.g. licht_an_aus, with allocation to the WomoLIN signal types Signal...
         LibSignalSetReset     birelay1_set_reset{ LibSignalSetReset() };
         LibSignalSetReset     birelay2_set_reset{ LibSignalSetReset() };
         LibSignalSetReset     birelay3_set_reset{ LibSignalSetReset() };
         LibSignalSetReset     birelay4_set_reset{ LibSignalSetReset() };

         LibSignalSetReset     birelay1_set_reset_status{ LibSignalSetReset() };
         LibSignalSetReset     birelay2_set_reset_status{ LibSignalSetReset() };
         LibSignalSetReset     birelay3_set_reset_status{ LibSignalSetReset() };
         LibSignalSetReset     birelay4_set_reset_status{ LibSignalSetReset() };

   };

}
