/* SPDX-License-Identifier: GPLv3-or-later */
/* Copyright (c) 2019 Project WomoLIN */
/* Author Myron Franze <myronfranze@web.de> */

#pragma once

#include "../../womolin/include/managerbase.h"
#include "../../womolin/include/unit.h"
#include "./hal/include/unit.h"

namespace womolin::board::mainunit
{
   
   using namespace womolin::interface::hal;
   using namespace womolin::signal;
   using namespace womolin::unit;
   using namespace womolin::manager;
   using namespace womolin::board::mainunit::hal;

   class Manager : public WomolinManagerBase 
   {
      public:
         Manager( IWomolinSerial & attSerial );
         ~Manager() = default;

      private:
         // properties of the board
         HalOutput HAL_BIRELAY_0 { HalOutput( DEV_ID::BIRELAY_0 ) }; 
         HalOutput HAL_BIRELAY_1 { HalOutput( DEV_ID::BIRELAY_1 ) }; 
         HalOutput HAL_BIRELAY_2 { HalOutput( DEV_ID::BIRELAY_2 ) }; 
         HalOutput HAL_BIRELAY_3 { HalOutput( DEV_ID::BIRELAY_3 ) }; 

         HalInput HAL_BIRELAY_0_STATUS { HalInput( DEV_ID::BIRELAY_0 ) }; 
         HalInput HAL_BIRELAY_1_STATUS { HalInput( DEV_ID::BIRELAY_1 ) }; 
         HalInput HAL_BIRELAY_2_STATUS { HalInput( DEV_ID::BIRELAY_2 ) }; 
         HalInput HAL_BIRELAY_3_STATUS { HalInput( DEV_ID::BIRELAY_3 ) }; 


         // will be generated by code generator
         // WomoLIN Units with allcation to the board units HAL_...
         WomolinOutput          LIB_BIRELAY_1{ WomolinOutput( HAL_BIRELAY_0 ) };
         WomolinOutput          LIB_BIRELAY_2{ WomolinOutput( HAL_BIRELAY_1 ) };
         WomolinOutput          LIB_BIRELAY_3{ WomolinOutput( HAL_BIRELAY_2 ) };
         WomolinOutput          LIB_BIRELAY_4{ WomolinOutput( HAL_BIRELAY_3 ) };

         WomolinInput          LIB_BIRELAY_1_STATUS{ WomolinInput( HAL_BIRELAY_0_STATUS) };
         WomolinInput          LIB_BIRELAY_2_STATUS{ WomolinInput( HAL_BIRELAY_1_STATUS) };
         WomolinInput          LIB_BIRELAY_3_STATUS{ WomolinInput( HAL_BIRELAY_2_STATUS) };
         WomolinInput          LIB_BIRELAY_4_STATUS{ WomolinInput( HAL_BIRELAY_3_STATUS) };


         // User Signals, e.g. licht_an_aus, with allocation to the WomoLIN signal types Signal...
         WomolinSignalSetReset     birelay1_set_reset{ WomolinSignalSetReset() };
         WomolinSignalSetReset     birelay2_set_reset{ WomolinSignalSetReset() };
         WomolinSignalSetReset     birelay3_set_reset{ WomolinSignalSetReset() };
         WomolinSignalSetReset     birelay4_set_reset{ WomolinSignalSetReset() };

         WomolinSignalSetReset     birelay1_set_reset_status{ WomolinSignalSetReset() };
         WomolinSignalSetReset     birelay2_set_reset_status{ WomolinSignalSetReset() };
         WomolinSignalSetReset     birelay3_set_reset_status{ WomolinSignalSetReset() };
         WomolinSignalSetReset     birelay4_set_reset_status{ WomolinSignalSetReset() };

   };

}
