FROM womoeclipse
MAINTAINER Norym

RUN sudo apt-get update && sudo apt-get install -y software-properties-common 
RUN sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
#RUN sudo apt-get update && sudo apt-get install -y g++-8 g++-8-arm-linux-gnueabi qemu-user
RUN sudo apt-get update && sudo apt-get install -y gcc-8 g++-8 gdb cmake make
