FROM womolinux 
MAINTAINER Norym

RUN sudo apt-get update && sudo apt-get install -y software-properties-common 
RUN sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test

RUN sudo apt-get update && \
    sudo apt-get install -y gcc-9 g++-9 qemu-user gdb cmake make libssl-dev && \
    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9 

RUN cd /tmp && \
   wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2 && \
   tar -xf gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2 && \
   sudo mv gcc-arm-none-eabi-9-2019-q4-major /opt  && \
   sudo rm -fr /tmp/gcc*

ENV PATH="${PATH}:/opt/gcc-arm-none-eabi-9-2019-q4-major/bin"
 

RUN sudo apt-get update && \
    sudo apt-get install -y libgtest-dev

RUN cd /tmp && \
   wget https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3.tar.gz && \
   tar -zxf cmake-3.17.3.tar.gz && \
   cd cmake-3.17.3 && \
   sudo ./bootstrap && \
   sudo make && \
   sudo make install && \
   sudo rm -fr /tmp/cmake*
 
