#pragma once

#include "../../lib/include/managerbase.h"
#include "../../lib/include/unit.h"
#include "./hal/include/unit.h"

namespace womolin::board::simulation
{
   class Manager : public womolin::manager::ManagerBase 
   {
      public:
         Manager( womolin::lib::common::interface::ISerial & serial );
         ~Manager() = default;

      private:
         // properties of the board, names identically to the lib with prefix HAL
         womolin::board::simulation::hal::unit::HalInputOutput    HAL_RELAY1{ womolin::board::simulation::hal::unit::HalInputOutput() }; 

         // will be generated by code generator
         // WomoLIN Units with allcation to the board units HAL_...
         womolin::unit::InputOutput                               RELAY1{ womolin::unit::InputOutput( HAL_RELAY1 ) };

         // User Signals, e.g. licht_an_aus, with allocation to the WomoLIN signal types Signal...
         womolin::signal::SignalSetReset                    licht_an_aus{ womolin::signal::SignalSetReset() };
   };

}
