#include "manager.h"
#include <iostream>

namespace womolin::board::simulation
{

   Manager::Manager( ISerial & serial ) : ManagerBase( serial )
   {
      // will be generated by code generator
      signalVector["relay1_set_reset"] = &relay1_set_reset;
      signalVector["relay2_set_reset"] = &relay2_set_reset;
      signalVector["led1_set_reset"] = &led1_set_reset;
      signalVector["led1_status"] = &led1_status;

      relay1_set_reset.AddUnit( &LIB_RELAY_1 );
      relay2_set_reset.AddUnit( &LIB_RELAY_2 );
      led1_set_reset.AddUnit( &LIB_LED_1 );
      led1_status.AddUnit( &LIB_LED_1_STATUS );
   }

}
