#include "manager.h"
#include <iostream>

namespace womolin::board::simulation
{
   Manager::Manager( womolin::lib::common::interface::ISerial & serial )
      : ManagerBase( serial )

   {
      std::cout << "Konstruktor Manager::Manager" << std::endl;

      // will be generated by code generator
      signalVector["licht_an_aus"] = &licht_an_aus;
      licht_an_aus.AddUnit( &RELAY1 );
   }

}
