#pragma once

#include "../../lib/include/managerbase.h"
#include "../../lib/include/unit.h"
#include "./hal/include/unit.h"

namespace womolin::board::simulation
{
   
   using namespace womolin::lib::manager;
   using namespace womolin::lib::interface::hal;
   using namespace womolin::unit;
   using namespace womolin::signal;
   using namespace womolin::board::simulation::hal;

   class Manager : public ManagerBase 
   {
      public:
         Manager( ISerial & serial );
         ~Manager() = default;

      private:
         // properties of the board
         HalOutput HAL_RELAY_0 { HalOutput( DEV_ID::RELAY_0 ) }; 
         HalOutput HAL_RELAY_1 { HalOutput( DEV_ID::RELAY_1 ) }; 
         HalOutput HAL_GPIO_LED_1 { HalOutput( DEV_ID::GPIO_LED_1 ) }; 

         HalInput HAL_LED_1_STATUS { HalInput( DEV_ID::GPIO_LED_1 ) }; 

         // will be generated by code generator
         // WomoLIN Units with allcation to the board units HAL_...
         Output          LIB_RELAY_1{ Output( HAL_RELAY_0 ) };
         Output          LIB_RELAY_2{ Output( HAL_RELAY_1 ) };
         Output          LIB_LED_1{ Output( HAL_GPIO_LED_1 ) };

         Input           LIB_LED_1_STATUS{ Input( HAL_LED_1_STATUS ) };


         // User Signals, e.g. licht_an_aus, with allocation to the WomoLIN signal types Signal...
         SignalSetReset     relay1_set_reset{ SignalSetReset() };
         SignalSetReset     relay2_set_reset{ SignalSetReset() };
         SignalSetReset     led1_set_reset{ SignalSetReset() };

         SignalSetReset     led1_status{ SignalSetReset() };

   };

}
