#pragma once

#include "../../lib/include/managerbase.h"
#include "../../lib/include/unit.h"
#include "./hal/include/unit.h"

namespace womolin::board::simulation
{
   
   using namespace womolin::lib::interface::hal;
   using namespace womolin::lib::signal;
   using namespace womolin::lib::unit;
   using namespace womolin::lib::manager;
   using namespace womolin::board::simulation::hal;

   class HalManager : public LibManagerBase 
   {
      public:
         HalManager( ILibSerial & serial );
         ~HalManager() = default;

      private:
         // properties of the board
         HalOutput HAL_RELAY_0 { HalOutput( DEV_ID::RELAY_0 ) }; 
         HalOutput HAL_RELAY_1 { HalOutput( DEV_ID::RELAY_1 ) }; 
         HalOutput HAL_GPIO_LED_1 { HalOutput( DEV_ID::GPIO_LED_1 ) }; 

         HalInput HAL_LED_1_STATUS { HalInput( DEV_ID::GPIO_LED_1 ) }; 

         // will be generated by code generator
         // WomoLIN Units with allcation to the board units HAL_...
         LibOutput          LIB_RELAY_1{ LibOutput( HAL_RELAY_0 ) };
         LibOutput          LIB_RELAY_2{ LibOutput( HAL_RELAY_1 ) };
         LibOutput          LIB_LED_1{ LibOutput( HAL_GPIO_LED_1 ) };

         LibInput           LIB_LED_1_STATUS{ LibInput( HAL_LED_1_STATUS ) };


         // User Signals, e.g. licht_an_aus, with allocation to the WomoLIN signal types Signal...
         LibSignalSetReset     relay1_set_reset{ LibSignalSetReset() };
         LibSignalSetReset     relay2_set_reset{ LibSignalSetReset() };
         LibSignalSetReset     led1_set_reset{ LibSignalSetReset() };

         LibSignalSetReset     led1_status{ LibSignalSetReset() };

   };

}
