#pragma once

#include "../../../lib/include/manager.h"
#include "../../../lib/include/signal.h"

namespace womolin::board::simulation
{
   class Manager : public womolin::manager::ManagerBase 
   {
      public:
         Manager( womolin::lib::common::interface::ISerial & serial, womolin::lib::common::interface::IProtocol & protocol );
         ~Manager() = default;

      private:
         // generated by code generator
         womolin::signal::SignalSetReset licht_an_aus { womolin::signal::SignalSetReset() };

   };

}
